puts "2 é menor do que 1? (2 < 1) #{2 < 1}"
puts "2 é maior do que 1? (2 > 1) #{2 > 1}"
puts "2 é igual do que 1? (2 = 1) #{2 == 1}"
puts "2 é diferente do que 1? (2 != 1) #{2 != 1}"
puts "2 é maior ou igual a 1? (2 >= 1) #{2 >= 1}"
puts "2 é menor ou igual a 1? (2 <= 1) #{2 <= 1}"
puts "lado esquerdo é menor que o lado direito? (2 <=> 4) #{2 <=> 4}"
puts "lado esquerdo é maior que o lado direito? (2 <=> 1) #{2 <=> 1}"
puts "lado esquerdo é igual o lado direito? (2 <=> 2) #{2 <=> 2}"